version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: ops-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"    # change left side to 27018 if 27017 is already used locally
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ops-api
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PORT: "5000"
      # IMPORTANT: service hostname is 'mongo' (not localhost)
      MONGO_URI: "mongodb://admin:admin123@mongo:27017/order_payment_db?authSource=admin"
      NODE_ENV: "production"
    ports:
      - "5000:5000"

volumes:
  mongo_data:
